spring:
  redis:
    host: 115.29.151.135
    port: 9736
    password:
    lettuce:
      pool:
#       ?????
        max-active: 8
#        ????????????-1?????
        max-wait: -1
#        ?????
        max-idle: 8
#        ?????
        min-idle: 0
#        ???????????????????????????????????????????????????
      shutdown-timeout: 100
    database: 1